; Generated by YAPL compiler Pass 4
; Source: /Users/jeff/go/src/github.com/gmofishsauce/wut4/lang/test/bootstrap.yapl

; Bootstrap startup code
; Stack initialized to 0x1000 (top of page 0)
_start:
    ldi r7, 4096
    jal main
    hlt

