; Generated by YAPL compiler Pass 4
; Source: test/brtest.yapl

; Bootstrap startup code
; Stack initialized to 0x1000 (top of page 0)
_start:
    ldi r7, 4096
    jal main
    hlt

; Runtime library for YAPL

__shru16:
; Shift R1 right by R2 bits (logical)
    tst r2, r0
    brz L_shru_done
L_shru_loop:
    srl r1
    adi r2, r2, -1
    tst r2, r0
    brnz L_shru_loop
L_shru_done:
    ret

; Function: Putc
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

Putc:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 96
    ssp r1 r2
    jal L_Putc_epilogue
L_Putc_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: isOverflow
; Visibility: STATIC, Return: UINT8
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

isOverflow:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r2 98
    lsp r1 r2
    ldi r2 1
    and r1, r1, r2
L_isOverflow_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: Emit
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 20 bytes (locals=0, virtregs=10, params=2, saved=6)

Emit:
    adi r7, r7, -20
    stw r4, r7, 12
    stw r5, r7, 14
    stw r6, r7, 16
    stw r1, r7, 10
    lsp r3, r0
    stw r3, r7, 18
    ldw r4, r7, 10
    stw r4, r7, 0
    ldw r1, r7, 0
    jal Putc
L_while0:
    jal isOverflow
    stw r1, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brnz L_cmp_t0
    ldi r6, 0
    br L_cmp_d1
L_cmp_t0:
    ldi r6, 1
L_cmp_d1:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz L_skip2
    jal L_endwhile1
L_skip2:
    ldw r4, r7, 10
    stw r4, r7, 8
    ldw r1, r7, 8
    jal Putc
    jal L_while0
L_endwhile1:
    jal L_Emit_epilogue
L_Emit_epilogue:
    ldw r3, r7, 18
    ssp r3, r0
    ldw r4, r7, 12
    ldw r5, r7, 14
    ldw r6, r7, 16
    adi r7, r7, 20
    ret

; Function: Putstr
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 28 bytes (locals=0, virtregs=18, params=2, saved=6)

Putstr:
    adi r7, r7, -28
    stw r4, r7, 20
    stw r5, r7, 22
    stw r6, r7, 24
    stw r1, r7, 18
    lsp r3, r0
    stw r3, r7, 26
L_while2:
    ldw r4, r7, 18
    stw r4, r7, 0
    ldw r5, r7, 0
    ldb r4, r5, 0
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brnz L_cmp_t3
    ldi r6, 0
    br L_cmp_d4
L_cmp_t3:
    ldi r6, 1
L_cmp_d4:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz L_skip5
    jal L_endwhile3
L_skip5:
    ldw r4, r7, 18
    stw r4, r7, 8
    ldw r5, r7, 8
    ldb r4, r5, 0
    stw r4, r7, 10
    ldw r1, r7, 10
    jal Emit
    ldw r4, r7, 18
    stw r4, r7, 12
    ldi r4, 1
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    add r6, r4, r5
    stw r6, r7, 16
    ldw r4, r7, 16
    stw r4, r7, 18
    jal L_while2
L_endwhile3:
    jal L_Putstr_epilogue
L_Putstr_epilogue:
    ldw r3, r7, 26
    ssp r3, r0
    ldw r4, r7, 20
    ldw r5, r7, 22
    ldw r6, r7, 24
    adi r7, r7, 28
    ret

; Function: PutHexNib
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 32 bytes (locals=0, virtregs=22, params=2, saved=6)

PutHexNib:
    adi r7, r7, -32
    stw r4, r7, 24
    stw r5, r7, 26
    stw r6, r7, 28
    stw r1, r7, 22
    lsp r3, r0
    stw r3, r7, 30
    ldw r4, r7, 22
    stw r4, r7, 0
    ldi r4, 10
    stw r4, r7, 2
    ldw r4, r7, 0
    ldw r5, r7, 2
    tst r4, r5
    brult L_cmp_t6
    ldi r6, 0
    br L_cmp_d7
L_cmp_t6:
    ldi r6, 1
L_cmp_d7:
    stw r6, r7, 4
    ldw r4, r7, 4
    adi r4, r4, 0
    brnz L_skip8
    jal L_else4
L_skip8:
    ldw r4, r7, 22
    stw r4, r7, 6
    ldi r4, 48
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    add r6, r4, r5
    stw r6, r7, 10
    ldw r1, r7, 10
    jal Emit
    jal L_endif5
L_else4:
    ldw r4, r7, 22
    stw r4, r7, 12
    ldi r4, 10
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    sub r6, r4, r5
    stw r6, r7, 16
    ldi r4, 65
    stw r4, r7, 18
    ldw r4, r7, 16
    ldw r5, r7, 18
    add r6, r4, r5
    stw r6, r7, 20
    ldw r1, r7, 20
    jal Emit
L_endif5:
    jal L_PutHexNib_epilogue
L_PutHexNib_epilogue:
    ldw r3, r7, 30
    ssp r3, r0
    ldw r4, r7, 24
    ldw r5, r7, 26
    ldw r6, r7, 28
    adi r7, r7, 32
    ret

; Function: PutHex
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 46 bytes (locals=0, virtregs=36, params=2, saved=6)

PutHex:
    adi r7, r7, -46
    stw r4, r7, 38
    stw r5, r7, 40
    stw r6, r7, 42
    stw r1, r7, 36
    lsp r3, r0
    stw r3, r7, 44
    ldw r4, r7, 36
    stw r4, r7, 0
    ldi r4, 12
    stw r4, r7, 2
    ldw r1, r7, 0
    ldw r2, r7, 2
    jal __shru16
    stw r1, r7, 4
    ldi r4, 15
    stw r4, r7, 6
    ldw r4, r7, 4
    ldw r5, r7, 6
    and r6, r4, r5
    stw r6, r7, 8
    ldw r1, r7, 8
    jal PutHexNib
    ldw r4, r7, 36
    stw r4, r7, 10
    ldi r4, 8
    stw r4, r7, 12
    ldw r1, r7, 10
    ldw r2, r7, 12
    jal __shru16
    stw r1, r7, 14
    ldi r4, 15
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    and r6, r4, r5
    stw r6, r7, 18
    ldw r1, r7, 18
    jal PutHexNib
    ldw r4, r7, 36
    stw r4, r7, 20
    ldi r4, 4
    stw r4, r7, 22
    ldw r1, r7, 20
    ldw r2, r7, 22
    jal __shru16
    stw r1, r7, 24
    ldi r4, 15
    stw r4, r7, 26
    ldw r4, r7, 24
    ldw r5, r7, 26
    and r6, r4, r5
    stw r6, r7, 28
    ldw r1, r7, 28
    jal PutHexNib
    ldw r4, r7, 36
    stw r4, r7, 30
    ldi r4, 15
    stw r4, r7, 32
    ldw r4, r7, 30
    ldw r5, r7, 32
    and r6, r4, r5
    stw r6, r7, 34
    ldw r1, r7, 34
    jal PutHexNib
    jal L_PutHex_epilogue
L_PutHex_epilogue:
    ldw r3, r7, 44
    ssp r3, r0
    ldw r4, r7, 38
    ldw r5, r7, 40
    ldw r6, r7, 42
    adi r7, r7, 46
    ret

; Function: main
; Visibility: STATIC, Return: VOID
; Params: 0, Frame: 50 bytes (locals=2, virtregs=40, params=0, saved=6)

main:
    adi r7, r7, -50
    stw r4, r7, 42
    stw r5, r7, 44
    stw r6, r7, 46
    lsp r3, r0
    stw r3, r7, 48
    ldi r4, 1
    stw r4, r7, 2
    ldi r4, 2
    stw r4, r7, 4
    ldi r4, 3
    stw r4, r7, 6
    ldi r4, 4
    stw r4, r7, 8
    ldi r4, 5
    stw r4, r7, 10
    ldi r4, 1
    stw r4, r7, 12
    ldw r4, r7, 12
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 12
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 12
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r3, r7, 12
    ldw r2, r7, 10
    ldw r1, r7, 8
    jal BigFunc
    adi r7, r7, 6
    stw r1, r7, 14
    ldw r4, r7, 14
    stw r4, r7, 0
    ldi r4, msgOk
    stw r4, r7, 16
    ldw r1, r7, 16
    jal Putstr
    ldw r4, r7, 0
    stw r4, r7, 18
    ldw r1, r7, 18
    jal PutHex
    ldi r4, msgNl
    stw r4, r7, 20
    ldw r1, r7, 20
    jal Putstr
    ldi r4, 1
    stw r4, r7, 22
    ldi r4, 2
    stw r4, r7, 24
    ldi r4, 3
    stw r4, r7, 26
    ldi r4, 4
    stw r4, r7, 28
    ldi r4, 5
    stw r4, r7, 30
    ldi r4, 0
    stw r4, r7, 32
    ldw r4, r7, 32
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 32
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 32
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r3, r7, 32
    ldw r2, r7, 30
    ldw r1, r7, 28
    jal BigFunc
    adi r7, r7, 6
    stw r1, r7, 34
    ldw r4, r7, 34
    stw r4, r7, 0
    ldi r4, msgSkp
    stw r4, r7, 36
    ldw r1, r7, 36
    jal Putstr
    ldw r4, r7, 0
    stw r4, r7, 38
    ldw r1, r7, 38
    jal PutHex
    ldi r4, msgNl
    stw r4, r7, 40
    ldw r1, r7, 40
    jal Putstr
    jal L_main_epilogue
L_main_epilogue:
    ldw r3, r7, 48
    ssp r3, r0
    ldw r4, r7, 42
    ldw r5, r7, 44
    ldw r6, r7, 46
    adi r7, r7, 50
    ret

; Function: BigFunc
; Visibility: PUBLIC, Return: UINT16
; Params: 6, Frame: 428 bytes (locals=30, virtregs=384, params=6, saved=6)

BigFunc:
    stw r4, r7, -8
    ldi r4, 428
    sub r7, r7, r4
    ldi r4, 422
    add r4, r7, r4
    stw r5, r4, 0
    ldi r4, 424
    add r4, r7, r4
    stw r6, r4, 0
    ldi r4, 414
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 416
    add r4, r7, r4
    stw r2, r4, 0
    ldi r4, 418
    add r4, r7, r4
    stw r3, r4, 0
    lsp r1, r0
    ldi r4, 426
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 432
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 30
    ldi r4, 0
    stw r4, r7, 32
    ldw r4, r7, 30
    ldw r5, r7, 32
    tst r4, r5
    brnz L_cmp_t9
    ldi r6, 0
    br L_cmp_d10
L_cmp_t9:
    ldi r6, 1
L_cmp_d10:
    stw r6, r7, 34
    ldw r4, r7, 34
    adi r4, r4, 0
    brnz L_skip11
    jal L_endif6
L_skip11:
    ldi r4, 414
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 36
    ldi r4, 416
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 38
    ldw r4, r7, 36
    ldw r5, r7, 38
    add r6, r4, r5
    stw r6, r7, 40
    ldw r4, r7, 40
    stw r4, r7, 28
    ldw r4, r7, 28
    stw r4, r7, 42
    ldi r4, 418
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 44
    ldw r4, r7, 42
    ldw r5, r7, 44
    add r6, r4, r5
    stw r6, r7, 46
    ldw r4, r7, 46
    stw r4, r7, 26
    ldw r4, r7, 26
    stw r4, r7, 48
    ldi r4, 428
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 50
    ldw r4, r7, 48
    ldw r5, r7, 50
    add r6, r4, r5
    stw r6, r7, 52
    ldw r4, r7, 52
    stw r4, r7, 24
    ldw r4, r7, 24
    stw r4, r7, 54
    ldi r4, 430
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 56
    ldw r4, r7, 54
    ldw r5, r7, 56
    add r6, r4, r5
    stw r6, r7, 58
    ldw r4, r7, 58
    stw r4, r7, 22
    ldw r4, r7, 22
    stw r4, r7, 60
    ldi r4, 432
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 62
    ldw r4, r7, 60
    ldw r5, r7, 62
    add r6, r4, r5
    ldi r3, 64
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 64
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 20
    ldw r4, r7, 20
    ldi r3, 66
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 28
    ldi r3, 68
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 66
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 68
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 70
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 70
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 18
    ldw r4, r7, 18
    ldi r3, 72
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 26
    ldi r3, 74
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 72
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 74
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 76
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 16
    ldw r4, r7, 16
    ldi r3, 78
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 24
    ldi r3, 80
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 80
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 82
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 82
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 14
    ldw r4, r7, 14
    ldi r3, 84
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 22
    ldi r3, 86
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 84
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 86
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 88
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 88
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 12
    ldw r4, r7, 12
    ldi r3, 90
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 20
    ldi r3, 92
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 90
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 92
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 94
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 94
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 10
    ldw r4, r7, 10
    ldi r3, 96
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 18
    ldi r3, 98
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 96
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 98
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 100
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 100
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 8
    ldw r4, r7, 8
    ldi r3, 102
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 16
    ldi r3, 104
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 102
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 104
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 106
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 106
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 6
    ldw r4, r7, 6
    ldi r3, 108
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 14
    ldi r3, 110
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 108
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 110
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 112
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 112
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 4
    ldw r4, r7, 4
    ldi r3, 114
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 12
    ldi r3, 116
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 114
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 116
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 118
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 118
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 2
    ldw r4, r7, 2
    ldi r3, 120
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 10
    ldi r3, 122
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 120
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 122
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 124
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 124
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 0
    ldw r4, r7, 28
    ldi r3, 126
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 0
    ldi r3, 128
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 126
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 128
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 130
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 414
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 132
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 130
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 132
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 134
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 134
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 26
    ldi r3, 136
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 2
    ldi r3, 138
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 136
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 138
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 140
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 416
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 142
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 140
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 142
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 144
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 144
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 26
    ldw r4, r7, 24
    ldi r3, 146
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 4
    ldi r3, 148
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 146
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 148
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 150
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 418
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 152
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 150
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 152
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 154
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 154
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 24
    ldw r4, r7, 22
    ldi r3, 156
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 6
    ldi r3, 158
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 156
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 158
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 160
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 428
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 162
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 160
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 162
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 164
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 164
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 22
    ldw r4, r7, 20
    ldi r3, 166
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 8
    ldi r3, 168
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 166
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 168
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 170
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 430
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 172
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 170
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 172
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 174
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 174
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 20
    ldw r4, r7, 18
    ldi r3, 176
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 0
    ldi r3, 178
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 176
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 178
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 180
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 432
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 182
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 180
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 182
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 184
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 184
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 18
    ldw r4, r7, 16
    ldi r3, 186
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 2
    ldi r3, 188
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 186
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 188
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 190
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 414
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 192
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 190
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 192
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 194
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 194
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 16
    ldw r4, r7, 14
    ldi r3, 196
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 4
    ldi r3, 198
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 196
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 198
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 200
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 416
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 202
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 200
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 202
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 204
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 204
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 14
    ldw r4, r7, 12
    ldi r3, 206
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 6
    ldi r3, 208
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 206
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 208
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 210
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 418
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 212
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 210
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 212
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 214
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 214
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 12
    ldw r4, r7, 10
    ldi r3, 216
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 8
    ldi r3, 218
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 216
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 218
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 220
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 428
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 222
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 220
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 222
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 224
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 224
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 10
    ldw r4, r7, 8
    ldi r3, 226
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 28
    ldi r3, 228
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 226
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 228
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 230
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 430
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 232
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 230
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 232
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 234
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 234
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 8
    ldw r4, r7, 6
    ldi r3, 236
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 26
    ldi r3, 238
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 236
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 238
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 240
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 432
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 242
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 240
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 242
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 244
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 244
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 6
    ldw r4, r7, 4
    ldi r3, 246
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 24
    ldi r3, 248
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 246
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 248
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 250
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 414
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 252
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 250
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 252
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 254
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 254
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldi r3, 256
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 22
    ldi r3, 258
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 256
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 258
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 260
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 416
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 262
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 260
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 262
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 264
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 264
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 2
    ldw r4, r7, 0
    ldi r3, 266
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 20
    ldi r3, 268
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 266
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 268
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 270
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 418
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 272
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 270
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 272
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 274
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 274
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 0
    ldw r4, r7, 28
    ldi r3, 276
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 18
    ldi r3, 278
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 276
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 278
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 280
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 428
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 282
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 280
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 282
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 284
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 284
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 26
    ldi r3, 286
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 16
    ldi r3, 288
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 286
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 288
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 290
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 430
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 292
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 290
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 292
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 294
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 294
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 26
    ldw r4, r7, 24
    ldi r3, 296
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 14
    ldi r3, 298
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 296
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 298
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 300
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 432
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 302
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 300
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 302
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 304
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 304
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 24
    ldw r4, r7, 22
    ldi r3, 306
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 12
    ldi r3, 308
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 306
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 308
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 310
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 414
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 312
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 310
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 312
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 314
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 314
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 22
    ldw r4, r7, 20
    ldi r3, 316
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 10
    ldi r3, 318
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 316
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 318
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 320
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 416
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 322
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 320
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 322
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 324
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 324
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 20
    ldw r4, r7, 28
    ldi r3, 326
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 26
    ldi r3, 328
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 326
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 328
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 330
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 330
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 332
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 24
    ldi r3, 334
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 332
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 334
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 336
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 336
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 338
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 22
    ldi r3, 340
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 338
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 340
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 342
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 342
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 344
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 20
    ldi r3, 346
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 344
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 346
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 348
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 348
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 350
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 18
    ldi r3, 352
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 350
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 352
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 354
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 354
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 356
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 16
    ldi r3, 358
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 356
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 358
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 360
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 360
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 362
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 14
    ldi r3, 364
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 362
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 364
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 366
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 366
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 368
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 12
    ldi r3, 370
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 368
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 370
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 372
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 372
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 374
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 10
    ldi r3, 376
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 374
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 376
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 378
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 378
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 380
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 8
    ldi r3, 382
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 380
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 382
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 384
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 384
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 386
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 6
    ldi r3, 388
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 386
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 388
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 390
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 390
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 392
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 4
    ldi r3, 394
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 392
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 394
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 396
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 396
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 398
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 2
    ldi r3, 400
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 398
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 400
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 402
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 402
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 404
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 0
    ldi r3, 406
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 404
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 406
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 408
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 408
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 28
    ldw r4, r7, 28
    ldi r3, 410
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 410
    add r1, r7, r1
    ldw r1, r1, 0
    jal L_BigFunc_epilogue
L_endif6:
    ldi r4, 0
    ldi r3, 412
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 412
    add r1, r7, r1
    ldw r1, r1, 0
    jal L_BigFunc_epilogue
L_BigFunc_epilogue:
    ldi r3, 426
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldi r5, 422
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 424
    add r6, r7, r6
    ldw r6, r6, 0
    ldi r4, 420
    add r4, r7, r4
    ldw r2, r4, 0
    ldi r4, 428
    add r7, r7, r4
    mv r4, r2
    ret


    .align 2

msgOk:
    .bytes "OK: \x00"
msgSkp:
    .bytes "SKIP: \x00"
msgNl:
    .bytes "\x0A\x00"
