; Generated by YAPL compiler Pass 4
; Source: hello.yapl

.bootstrap

; Function: Main
; Visibility: PUBLIC, Return: VOID
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

Main:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r4, hello
    stw r4, r7, 0
    ldw r1, r7, 0
    jal Putstr
    jal l_Main_epilogue
l_Main_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: Putc
; Visibility: PUBLIC, Return: UINT8
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

Putc:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 96
    ssp r1 r2
l_Putc_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: isOverflow
; Visibility: STATIC, Return: UINT8
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

isOverflow:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r2 98
    lsp r1 r2
    ldi r2 1
    and r1, r1, r2
l_isOverflow_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: Putstr
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 32 bytes (locals=0, virtregs=22, params=2, saved=6)

Putstr:
    adi r7, r7, -32
    stw r4, r7, 24
    stw r5, r7, 26
    stw r6, r7, 28
    stw r1, r7, 22
    lsp r3, r0
    stw r3, r7, 30
l_while0:
    ldw r4, r7, 22
    stw r4, r7, 0
    ldw r5, r7, 0
    ldb r4, r5, 0
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brnz l_cmp_t0
    ldi r6, 0
    br l_cmp_d1
l_cmp_t0:
    ldi r6, 1
l_cmp_d1:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz l_skip2
    jal l_endwhile1
l_skip2:
    ldw r4, r7, 22
    stw r4, r7, 8
    ldw r5, r7, 8
    ldb r4, r5, 0
    stw r4, r7, 10
    ldw r1, r7, 10
    jal Putc
    stw r1, r7, 12
    jal isOverflow
    stw r1, r7, 14
    ldw r4, r7, 14
    adi r4, r4, 0
    brnz l_skip3
    jal l_endif2
l_skip3:
    jal l_while0
l_endif2:
    ldw r4, r7, 22
    stw r4, r7, 16
    ldi r4, 1
    stw r4, r7, 18
    ldw r4, r7, 16
    ldw r5, r7, 18
    add r6, r4, r5
    stw r6, r7, 20
    ldw r4, r7, 20
    stw r4, r7, 22
    jal l_while0
l_endwhile1:
    jal l_Putstr_epilogue
l_Putstr_epilogue:
    ldw r3, r7, 30
    ssp r3, r0
    ldw r4, r7, 24
    ldw r5, r7, 26
    ldw r6, r7, 28
    adi r7, r7, 32
    ret


    .align 2

hello:
    .bytes "hello, world.\x0A\x00"
