; Generated by YAPL compiler Pass 4
; Source: test/sdtest.yapl

; Bootstrap startup code
; Stack initialized to 0x1000 (top of page 0)
_start:
    ldi r7, 4096
    jal main
    hlt

; Runtime library for YAPL

__shru16:
; Shift R1 right by R2 bits (logical)
    tst r2, r0
    brz L_shru_done
L_shru_loop:
    srl r1
    adi r2, r2, -1
    tst r2, r0
    brnz L_shru_loop
L_shru_done:
    ret

; Function: SpiSend
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

SpiSend:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 100
    ssp r1 r2
    jal L_SpiSend_epilogue
L_SpiSend_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: SpiRecv
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

SpiRecv:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r2 100
    lsp r1 r2
L_SpiRecv_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: SpiRx
; Visibility: PUBLIC, Return: UINT16
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

SpiRx:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r2 100
    lsp r1 r2
L_SpiRx_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: SpiSel
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

SpiSel:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 101
    ssp r1 r2
    jal L_SpiSel_epilogue
L_SpiSel_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: MapPage
; Visibility: PUBLIC, Return: VOID
; Params: 2, Frame: 14 bytes (locals=0, virtregs=2, params=4, saved=6)

MapPage:
    adi r7, r7, -14
    stw r4, r7, 6
    stw r5, r7, 8
    stw r6, r7, 10
    stw r1, r7, 2
    stw r2, r7, 4
    lsp r3, r0
    stw r3, r7, 12
    ssp r2 r1
    jal L_MapPage_epilogue
L_MapPage_epilogue:
    ldw r3, r7, 12
    ssp r3, r0
    ldw r4, r7, 6
    ldw r5, r7, 8
    ldw r6, r7, 10
    adi r7, r7, 14
    ret

; Function: StoreByte
; Visibility: PUBLIC, Return: VOID
; Params: 2, Frame: 14 bytes (locals=0, virtregs=2, params=4, saved=6)

StoreByte:
    adi r7, r7, -14
    stw r4, r7, 6
    stw r5, r7, 8
    stw r6, r7, 10
    stw r1, r7, 2
    stw r2, r7, 4
    lsp r3, r0
    stw r3, r7, 12
    stb r2, r1, 0
    jal L_StoreByte_epilogue
L_StoreByte_epilogue:
    ldw r3, r7, 12
    ssp r3, r0
    ldw r4, r7, 6
    ldw r5, r7, 8
    ldw r6, r7, 10
    adi r7, r7, 14
    ret

; Function: LoadByte
; Visibility: PUBLIC, Return: UINT8
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

LoadByte:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldb r1, r1, 0
L_LoadByte_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: Putc
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

Putc:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 96
    ssp r1 r2
    jal L_Putc_epilogue
L_Putc_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: isOverflow
; Visibility: STATIC, Return: UINT8
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

isOverflow:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r2 98
    lsp r1 r2
    ldi r2 1
    and r1, r1, r2
L_isOverflow_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: Emit
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 20 bytes (locals=0, virtregs=10, params=2, saved=6)

Emit:
    adi r7, r7, -20
    stw r4, r7, 12
    stw r5, r7, 14
    stw r6, r7, 16
    stw r1, r7, 10
    lsp r3, r0
    stw r3, r7, 18
    ldw r4, r7, 10
    stw r4, r7, 0
    ldw r1, r7, 0
    jal Putc
L_while0:
    jal isOverflow
    stw r1, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brnz L_cmp_t0
    ldi r6, 0
    br L_cmp_d1
L_cmp_t0:
    ldi r6, 1
L_cmp_d1:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz L_skip2
    jal L_endwhile1
L_skip2:
    ldw r4, r7, 10
    stw r4, r7, 8
    ldw r1, r7, 8
    jal Putc
    jal L_while0
L_endwhile1:
    jal L_Emit_epilogue
L_Emit_epilogue:
    ldw r3, r7, 18
    ssp r3, r0
    ldw r4, r7, 12
    ldw r5, r7, 14
    ldw r6, r7, 16
    adi r7, r7, 20
    ret

; Function: Putstr
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 28 bytes (locals=0, virtregs=18, params=2, saved=6)

Putstr:
    adi r7, r7, -28
    stw r4, r7, 20
    stw r5, r7, 22
    stw r6, r7, 24
    stw r1, r7, 18
    lsp r3, r0
    stw r3, r7, 26
L_while2:
    ldw r4, r7, 18
    stw r4, r7, 0
    ldw r5, r7, 0
    ldb r4, r5, 0
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brnz L_cmp_t3
    ldi r6, 0
    br L_cmp_d4
L_cmp_t3:
    ldi r6, 1
L_cmp_d4:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz L_skip5
    jal L_endwhile3
L_skip5:
    ldw r4, r7, 18
    stw r4, r7, 8
    ldw r5, r7, 8
    ldb r4, r5, 0
    stw r4, r7, 10
    ldw r1, r7, 10
    jal Emit
    ldw r4, r7, 18
    stw r4, r7, 12
    ldi r4, 1
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    add r6, r4, r5
    stw r6, r7, 16
    ldw r4, r7, 16
    stw r4, r7, 18
    jal L_while2
L_endwhile3:
    jal L_Putstr_epilogue
L_Putstr_epilogue:
    ldw r3, r7, 26
    ssp r3, r0
    ldw r4, r7, 20
    ldw r5, r7, 22
    ldw r6, r7, 24
    adi r7, r7, 28
    ret

; Function: PutHexNib
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 32 bytes (locals=0, virtregs=22, params=2, saved=6)

PutHexNib:
    adi r7, r7, -32
    stw r4, r7, 24
    stw r5, r7, 26
    stw r6, r7, 28
    stw r1, r7, 22
    lsp r3, r0
    stw r3, r7, 30
    ldw r4, r7, 22
    stw r4, r7, 0
    ldi r4, 10
    stw r4, r7, 2
    ldw r4, r7, 0
    ldw r5, r7, 2
    tst r4, r5
    brult L_cmp_t6
    ldi r6, 0
    br L_cmp_d7
L_cmp_t6:
    ldi r6, 1
L_cmp_d7:
    stw r6, r7, 4
    ldw r4, r7, 4
    adi r4, r4, 0
    brnz L_skip8
    jal L_else4
L_skip8:
    ldw r4, r7, 22
    stw r4, r7, 6
    ldi r4, 48
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    add r6, r4, r5
    stw r6, r7, 10
    ldw r1, r7, 10
    jal Emit
    jal L_endif5
L_else4:
    ldw r4, r7, 22
    stw r4, r7, 12
    ldi r4, 10
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    sub r6, r4, r5
    stw r6, r7, 16
    ldi r4, 65
    stw r4, r7, 18
    ldw r4, r7, 16
    ldw r5, r7, 18
    add r6, r4, r5
    stw r6, r7, 20
    ldw r1, r7, 20
    jal Emit
L_endif5:
    jal L_PutHexNib_epilogue
L_PutHexNib_epilogue:
    ldw r3, r7, 30
    ssp r3, r0
    ldw r4, r7, 24
    ldw r5, r7, 26
    ldw r6, r7, 28
    adi r7, r7, 32
    ret

; Function: PutHexByte
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 26 bytes (locals=0, virtregs=16, params=2, saved=6)

PutHexByte:
    adi r7, r7, -26
    stw r4, r7, 18
    stw r5, r7, 20
    stw r6, r7, 22
    stw r1, r7, 16
    lsp r3, r0
    stw r3, r7, 24
    ldw r4, r7, 16
    stw r4, r7, 0
    ldi r4, 4
    stw r4, r7, 2
    ldw r1, r7, 0
    ldw r2, r7, 2
    jal __shru16
    stw r1, r7, 4
    ldi r4, 15
    stw r4, r7, 6
    ldw r4, r7, 4
    ldw r5, r7, 6
    and r6, r4, r5
    stw r6, r7, 8
    ldw r1, r7, 8
    jal PutHexNib
    ldw r4, r7, 16
    stw r4, r7, 10
    ldi r4, 15
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    and r6, r4, r5
    stw r6, r7, 14
    ldw r1, r7, 14
    jal PutHexNib
    jal L_PutHexByte_epilogue
L_PutHexByte_epilogue:
    ldw r3, r7, 24
    ssp r3, r0
    ldw r4, r7, 18
    ldw r5, r7, 20
    ldw r6, r7, 22
    adi r7, r7, 26
    ret

; Function: Pump
; Visibility: PUBLIC, Return: VOID
; Params: 0, Frame: 12 bytes (locals=2, virtregs=2, params=0, saved=6)

Pump:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    lsp r3, r0
    stw r3, r7, 10
    jal SpiRecv
    stw r1, r7, 2
    ldw r4, r7, 2
    stb r4, r7, 1
    jal L_Pump_epilogue
L_Pump_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: Pump5
; Visibility: PUBLIC, Return: VOID
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

Pump5:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    jal Pump
    jal Pump
    jal Pump
    jal Pump
    jal Pump
    jal L_Pump5_epilogue
L_Pump5_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: WaitResp
; Visibility: PUBLIC, Return: UINT16
; Params: 0, Frame: 38 bytes (locals=4, virtregs=26, params=0, saved=6)

WaitResp:
    adi r7, r7, -38
    stw r4, r7, 30
    stw r5, r7, 32
    stw r6, r7, 34
    lsp r3, r0
    stw r3, r7, 36
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 4
    stw r4, r7, 0
L_while6:
    ldw r4, r7, 0
    stw r4, r7, 6
    ldi r4, 32
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    tst r4, r5
    brult L_cmp_t9
    ldi r6, 0
    br L_cmp_d10
L_cmp_t9:
    ldi r6, 1
L_cmp_d10:
    stw r6, r7, 10
    ldw r4, r7, 10
    adi r4, r4, 0
    brnz L_skip11
    jal L_endwhile7
L_skip11:
    jal SpiRx
    stw r1, r7, 12
    ldw r4, r7, 12
    stw r4, r7, 2
    ldw r4, r7, 2
    stw r4, r7, 14
    ldi r4, 255
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    tst r4, r5
    brnz L_cmp_t12
    ldi r6, 0
    br L_cmp_d13
L_cmp_t12:
    ldi r6, 1
L_cmp_d13:
    stw r6, r7, 18
    ldw r4, r7, 18
    adi r4, r4, 0
    brnz L_skip14
    jal L_endif8
L_skip14:
    ldw r4, r7, 2
    stw r4, r7, 20
    ldw r1, r7, 20
    jal L_WaitResp_epilogue
L_endif8:
    ldw r4, r7, 0
    stw r4, r7, 22
    ldi r4, 1
    stw r4, r7, 24
    ldw r4, r7, 22
    ldw r5, r7, 24
    add r6, r4, r5
    stw r6, r7, 26
    ldw r4, r7, 26
    stw r4, r7, 0
    jal L_while6
L_endwhile7:
    ldi r4, 255
    stw r4, r7, 28
    ldw r1, r7, 28
    jal L_WaitResp_epilogue
L_WaitResp_epilogue:
    ldw r3, r7, 36
    ssp r3, r0
    ldw r4, r7, 30
    ldw r5, r7, 32
    ldw r6, r7, 34
    adi r7, r7, 38
    ret

; Function: SdCmd
; Visibility: PUBLIC, Return: UINT8
; Params: 3, Frame: 68 bytes (locals=2, virtregs=52, params=6, saved=6)

SdCmd:
    stw r4, r7, -8
    ldi r4, 68
    sub r7, r7, r4
    stw r5, r7, 62
    ldi r4, 64
    add r4, r7, r4
    stw r6, r4, 0
    stw r1, r7, 54
    stw r2, r7, 56
    stw r3, r7, 58
    lsp r1, r0
    ldi r4, 66
    add r4, r7, r4
    stw r1, r4, 0
    ldw r4, r7, 54
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    brz L_cmp_t15
    ldi r6, 0
    br L_cmp_d16
L_cmp_t15:
    ldi r6, 1
L_cmp_d16:
    stw r6, r7, 6
    ldw r4, r7, 6
    adi r4, r4, 0
    brnz L_skip17
    jal L_else9
L_skip17:
    ldi r4, 149
    stw r4, r7, 8
    ldw r4, r7, 8
    stb r4, r7, 1
    jal L_endif10
L_else9:
    ldw r4, r7, 54
    stw r4, r7, 10
    ldi r4, 8
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    tst r4, r5
    brz L_cmp_t18
    ldi r6, 0
    br L_cmp_d19
L_cmp_t18:
    ldi r6, 1
L_cmp_d19:
    stw r6, r7, 14
    ldw r4, r7, 14
    adi r4, r4, 0
    brnz L_skip20
    jal L_else11
L_skip20:
    ldi r4, 135
    stw r4, r7, 16
    ldw r4, r7, 16
    stb r4, r7, 1
    jal L_endif12
L_else11:
    ldi r4, 255
    stw r4, r7, 18
    ldw r4, r7, 18
    stb r4, r7, 1
L_endif12:
L_endif10:
    ldw r4, r7, 54
    stw r4, r7, 20
    ldi r4, 64
    stw r4, r7, 22
    ldw r4, r7, 20
    ldw r5, r7, 22
    or r6, r4, r5
    stw r6, r7, 24
    ldw r1, r7, 24
    jal SpiSend
    ldw r4, r7, 56
    stw r4, r7, 26
    ldi r4, 8
    stw r4, r7, 28
    ldw r1, r7, 26
    ldw r2, r7, 28
    jal __shru16
    stw r1, r7, 30
    ldw r1, r7, 30
    jal SpiSend
    ldw r4, r7, 56
    stw r4, r7, 32
    ldi r4, 255
    stw r4, r7, 34
    ldw r4, r7, 32
    ldw r5, r7, 34
    and r6, r4, r5
    stw r6, r7, 36
    ldw r1, r7, 36
    jal SpiSend
    ldw r4, r7, 58
    stw r4, r7, 38
    ldi r4, 8
    stw r4, r7, 40
    ldw r1, r7, 38
    ldw r2, r7, 40
    jal __shru16
    stw r1, r7, 42
    ldw r1, r7, 42
    jal SpiSend
    ldw r4, r7, 58
    stw r4, r7, 44
    ldi r4, 255
    stw r4, r7, 46
    ldw r4, r7, 44
    ldw r5, r7, 46
    and r6, r4, r5
    stw r6, r7, 48
    ldw r1, r7, 48
    jal SpiSend
    ldb r4, r7, 1
    stw r4, r7, 50
    ldw r1, r7, 50
    jal SpiSend
    jal WaitResp
    stw r1, r7, 52
    ldw r1, r7, 52
    jal L_SdCmd_epilogue
L_SdCmd_epilogue:
    ldi r3, 66
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldw r5, r7, 62
    ldi r6, 64
    add r6, r7, r6
    ldw r6, r6, 0
    ldw r2, r7, 60
    ldi r4, 68
    add r7, r7, r4
    mv r4, r2
    ret

; Function: SdInit0
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 50 bytes (locals=4, virtregs=38, params=0, saved=6)

SdInit0:
    adi r7, r7, -50
    stw r4, r7, 42
    stw r5, r7, 44
    stw r6, r7, 46
    lsp r3, r0
    stw r3, r7, 48
    ldi r4, 1
    stw r4, r7, 4
    ldw r1, r7, 4
    jal SpiSel
    ldi r4, 0
    stw r4, r7, 6
    ldw r4, r7, 6
    stw r4, r7, 2
L_while13:
    ldw r4, r7, 2
    stw r4, r7, 8
    ldi r4, 12
    stw r4, r7, 10
    ldw r4, r7, 8
    ldw r5, r7, 10
    tst r4, r5
    brult L_cmp_t21
    ldi r6, 0
    br L_cmp_d22
L_cmp_t21:
    ldi r6, 1
L_cmp_d22:
    stw r6, r7, 12
    ldw r4, r7, 12
    adi r4, r4, 0
    brnz L_skip23
    jal L_endwhile14
L_skip23:
    ldi r4, 255
    stw r4, r7, 14
    ldw r1, r7, 14
    jal SpiSend
    ldw r4, r7, 2
    stw r4, r7, 16
    ldi r4, 1
    stw r4, r7, 18
    ldw r4, r7, 16
    ldw r5, r7, 18
    add r6, r4, r5
    stw r6, r7, 20
    ldw r4, r7, 20
    stw r4, r7, 2
    jal L_while13
L_endwhile14:
    ldi r4, 0
    stw r4, r7, 22
    ldw r1, r7, 22
    jal SpiSel
    ldi r4, 0
    stw r4, r7, 24
    ldi r4, 0
    stw r4, r7, 26
    ldi r4, 0
    stw r4, r7, 28
    ldw r3, r7, 28
    ldw r2, r7, 26
    ldw r1, r7, 24
    jal SdCmd
    stw r1, r7, 30
    ldw r4, r7, 30
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 32
    ldi r4, 1
    stw r4, r7, 34
    ldw r4, r7, 32
    ldw r5, r7, 34
    tst r4, r5
    brnz L_cmp_t24
    ldi r6, 0
    br L_cmp_d25
L_cmp_t24:
    ldi r6, 1
L_cmp_d25:
    stw r6, r7, 36
    ldw r4, r7, 36
    adi r4, r4, 0
    brnz L_skip26
    jal L_endif15
L_skip26:
    ldi r4, 1
    stw r4, r7, 38
    ldw r1, r7, 38
    jal L_SdInit0_epilogue
L_endif15:
    jal Pump
    ldi r4, 0
    stw r4, r7, 40
    ldw r1, r7, 40
    jal L_SdInit0_epilogue
L_SdInit0_epilogue:
    ldw r3, r7, 48
    ssp r3, r0
    ldw r4, r7, 42
    ldw r5, r7, 44
    ldw r6, r7, 46
    adi r7, r7, 50
    ret

; Function: SdInit1
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 44 bytes (locals=2, virtregs=34, params=0, saved=6)

SdInit1:
    adi r7, r7, -44
    stw r4, r7, 36
    stw r5, r7, 38
    stw r6, r7, 40
    lsp r3, r0
    stw r3, r7, 42
    ldi r4, 8
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldi r4, 426
    stw r4, r7, 6
    ldw r3, r7, 6
    ldw r2, r7, 4
    ldw r1, r7, 2
    jal SdCmd
    stw r1, r7, 8
    ldw r4, r7, 8
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 10
    ldi r4, 1
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    tst r4, r5
    brnz L_cmp_t27
    ldi r6, 0
    br L_cmp_d28
L_cmp_t27:
    ldi r6, 1
L_cmp_d28:
    stw r6, r7, 14
    ldw r4, r7, 14
    adi r4, r4, 0
    brnz L_skip29
    jal L_endif16
L_skip29:
    ldi r4, 2
    stw r4, r7, 16
    ldw r1, r7, 16
    jal L_SdInit1_epilogue
L_endif16:
    jal Pump5
    ldi r4, 58
    stw r4, r7, 18
    ldi r4, 0
    stw r4, r7, 20
    ldi r4, 0
    stw r4, r7, 22
    ldw r3, r7, 22
    ldw r2, r7, 20
    ldw r1, r7, 18
    jal SdCmd
    stw r1, r7, 24
    ldw r4, r7, 24
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 26
    ldi r4, 1
    stw r4, r7, 28
    ldw r4, r7, 26
    ldw r5, r7, 28
    tst r4, r5
    brnz L_cmp_t30
    ldi r6, 0
    br L_cmp_d31
L_cmp_t30:
    ldi r6, 1
L_cmp_d31:
    stw r6, r7, 30
    ldw r4, r7, 30
    adi r4, r4, 0
    brnz L_skip32
    jal L_endif17
L_skip32:
    ldi r4, 3
    stw r4, r7, 32
    ldw r1, r7, 32
    jal L_SdInit1_epilogue
L_endif17:
    jal Pump5
    ldi r4, 0
    stw r4, r7, 34
    ldw r1, r7, 34
    jal L_SdInit1_epilogue
L_SdInit1_epilogue:
    ldw r3, r7, 42
    ssp r3, r0
    ldw r4, r7, 36
    ldw r5, r7, 38
    ldw r6, r7, 40
    adi r7, r7, 44
    ret

; Function: SdInit2
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 44 bytes (locals=2, virtregs=34, params=0, saved=6)

SdInit2:
    adi r7, r7, -44
    stw r4, r7, 36
    stw r5, r7, 38
    stw r6, r7, 40
    lsp r3, r0
    stw r3, r7, 42
    ldi r4, 55
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldi r4, 0
    stw r4, r7, 6
    ldw r3, r7, 6
    ldw r2, r7, 4
    ldw r1, r7, 2
    jal SdCmd
    stw r1, r7, 8
    ldw r4, r7, 8
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 10
    ldi r4, 1
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    tst r4, r5
    brnz L_cmp_t33
    ldi r6, 0
    br L_cmp_d34
L_cmp_t33:
    ldi r6, 1
L_cmp_d34:
    stw r6, r7, 14
    ldw r4, r7, 14
    adi r4, r4, 0
    brnz L_skip35
    jal L_endif18
L_skip35:
    ldi r4, 4
    stw r4, r7, 16
    ldw r1, r7, 16
    jal L_SdInit2_epilogue
L_endif18:
    jal Pump
    ldi r4, 41
    stw r4, r7, 18
    ldi r4, 16384
    stw r4, r7, 20
    ldi r4, 0
    stw r4, r7, 22
    ldw r3, r7, 22
    ldw r2, r7, 20
    ldw r1, r7, 18
    jal SdCmd
    stw r1, r7, 24
    ldw r4, r7, 24
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 26
    ldi r4, 0
    stw r4, r7, 28
    ldw r4, r7, 26
    ldw r5, r7, 28
    tst r4, r5
    brnz L_cmp_t36
    ldi r6, 0
    br L_cmp_d37
L_cmp_t36:
    ldi r6, 1
L_cmp_d37:
    stw r6, r7, 30
    ldw r4, r7, 30
    adi r4, r4, 0
    brnz L_skip38
    jal L_endif19
L_skip38:
    ldi r4, 5
    stw r4, r7, 32
    ldw r1, r7, 32
    jal L_SdInit2_epilogue
L_endif19:
    jal Pump
    ldi r4, 0
    stw r4, r7, 34
    ldw r1, r7, 34
    jal L_SdInit2_epilogue
L_SdInit2_epilogue:
    ldw r3, r7, 42
    ssp r3, r0
    ldw r4, r7, 36
    ldw r5, r7, 38
    ldw r6, r7, 40
    adi r7, r7, 44
    ret

; Function: SdInit
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 32 bytes (locals=2, virtregs=22, params=0, saved=6)

SdInit:
    adi r7, r7, -32
    stw r4, r7, 24
    stw r5, r7, 26
    stw r6, r7, 28
    lsp r3, r0
    stw r3, r7, 30
    jal SdInit0
    stw r1, r7, 2
    ldw r4, r7, 2
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 4
    ldi r4, 0
    stw r4, r7, 6
    ldw r4, r7, 4
    ldw r5, r7, 6
    tst r4, r5
    brnz L_cmp_t39
    ldi r6, 0
    br L_cmp_d40
L_cmp_t39:
    ldi r6, 1
L_cmp_d40:
    stw r6, r7, 8
    ldw r4, r7, 8
    adi r4, r4, 0
    brnz L_skip41
    jal L_endif20
L_skip41:
    ldb r4, r7, 1
    stw r4, r7, 10
    ldw r1, r7, 10
    jal L_SdInit_epilogue
L_endif20:
    jal SdInit1
    stw r1, r7, 12
    ldw r4, r7, 12
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 14
    ldi r4, 0
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    tst r4, r5
    brnz L_cmp_t42
    ldi r6, 0
    br L_cmp_d43
L_cmp_t42:
    ldi r6, 1
L_cmp_d43:
    stw r6, r7, 18
    ldw r4, r7, 18
    adi r4, r4, 0
    brnz L_skip44
    jal L_endif21
L_skip44:
    ldb r4, r7, 1
    stw r4, r7, 20
    ldw r1, r7, 20
    jal L_SdInit_epilogue
L_endif21:
    jal SdInit2
    stw r1, r7, 22
    ldw r1, r7, 22
    jal L_SdInit_epilogue
L_SdInit_epilogue:
    ldw r3, r7, 30
    ssp r3, r0
    ldw r4, r7, 24
    ldw r5, r7, 26
    ldw r6, r7, 28
    adi r7, r7, 32
    ret

; Function: SdReadSec
; Visibility: PUBLIC, Return: UINT8
; Params: 2, Frame: 70 bytes (locals=6, virtregs=52, params=4, saved=6)

SdReadSec:
    stw r4, r7, -8
    ldi r4, 70
    sub r7, r7, r4
    ldi r4, 64
    add r4, r7, r4
    stw r5, r4, 0
    ldi r4, 66
    add r4, r7, r4
    stw r6, r4, 0
    stw r1, r7, 58
    stw r2, r7, 60
    lsp r1, r0
    ldi r4, 68
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 17
    stw r4, r7, 6
    ldi r4, 0
    stw r4, r7, 8
    ldw r4, r7, 58
    stw r4, r7, 10
    ldw r3, r7, 10
    ldw r2, r7, 8
    ldw r1, r7, 6
    jal SdCmd
    stw r1, r7, 12
    ldw r4, r7, 12
    stb r4, r7, 5
    ldb r4, r7, 5
    stw r4, r7, 14
    ldi r4, 0
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    tst r4, r5
    brnz L_cmp_t45
    ldi r6, 0
    br L_cmp_d46
L_cmp_t45:
    ldi r6, 1
L_cmp_d46:
    stw r6, r7, 18
    ldw r4, r7, 18
    adi r4, r4, 0
    brnz L_skip47
    jal L_endif22
L_skip47:
    ldb r4, r7, 5
    stw r4, r7, 20
    ldw r1, r7, 20
    jal L_SdReadSec_epilogue
L_endif22:
    jal WaitResp
    stw r1, r7, 22
    ldw r4, r7, 22
    stw r4, r7, 0
    ldw r4, r7, 0
    stw r4, r7, 24
    ldi r4, 254
    stw r4, r7, 26
    ldw r4, r7, 24
    ldw r5, r7, 26
    tst r4, r5
    brnz L_cmp_t48
    ldi r6, 0
    br L_cmp_d49
L_cmp_t48:
    ldi r6, 1
L_cmp_d49:
    stw r6, r7, 28
    ldw r4, r7, 28
    adi r4, r4, 0
    brnz L_skip50
    jal L_endif23
L_skip50:
    ldi r4, 255
    stw r4, r7, 30
    ldw r1, r7, 30
    jal L_SdReadSec_epilogue
L_endif23:
    ldi r4, 0
    stw r4, r7, 32
    ldw r4, r7, 32
    stw r4, r7, 2
L_while24:
    ldw r4, r7, 2
    stw r4, r7, 34
    ldi r4, 512
    stw r4, r7, 36
    ldw r4, r7, 34
    ldw r5, r7, 36
    tst r4, r5
    brult L_cmp_t51
    ldi r6, 0
    br L_cmp_d52
L_cmp_t51:
    ldi r6, 1
L_cmp_d52:
    stw r6, r7, 38
    ldw r4, r7, 38
    adi r4, r4, 0
    brnz L_skip53
    jal L_endwhile25
L_skip53:
    jal SpiRecv
    stw r1, r7, 40
    ldw r4, r7, 40
    stb r4, r7, 5
    ldw r4, r7, 60
    stw r4, r7, 42
    ldw r4, r7, 2
    stw r4, r7, 44
    ldw r4, r7, 42
    ldw r5, r7, 44
    add r6, r4, r5
    stw r6, r7, 46
    ldb r4, r7, 5
    stw r4, r7, 48
    ldw r2, r7, 48
    ldw r1, r7, 46
    jal StoreByte
    ldw r4, r7, 2
    stw r4, r7, 50
    ldi r4, 1
    stw r4, r7, 52
    ldw r4, r7, 50
    ldw r5, r7, 52
    add r6, r4, r5
    stw r6, r7, 54
    ldw r4, r7, 54
    stw r4, r7, 2
    jal L_while24
L_endwhile25:
    jal Pump
    jal Pump
    ldi r4, 0
    stw r4, r7, 56
    ldw r1, r7, 56
    jal L_SdReadSec_epilogue
L_SdReadSec_epilogue:
    ldi r3, 68
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldi r5, 64
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 66
    add r6, r7, r6
    ldw r6, r6, 0
    ldw r2, r7, 62
    ldi r4, 70
    add r7, r7, r4
    mv r4, r2
    ret

; Function: ReadSecs
; Visibility: PUBLIC, Return: UINT8
; Params: 0, Frame: 62 bytes (locals=8, virtregs=46, params=0, saved=6)

ReadSecs:
    adi r7, r7, -62
    stw r4, r7, 54
    stw r5, r7, 56
    stw r6, r7, 58
    lsp r3, r0
    stw r3, r7, 60
    ldi r4, 0
    stw r4, r7, 8
    ldw r4, r7, 8
    stw r4, r7, 4
    ldi r4, 4096
    stw r4, r7, 10
    ldw r4, r7, 10
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 12
    ldw r4, r7, 12
    stw r4, r7, 0
L_while26:
    ldw r4, r7, 0
    stw r4, r7, 14
    ldi r4, 16
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    tst r4, r5
    brult L_cmp_t54
    ldi r6, 0
    br L_cmp_d55
L_cmp_t54:
    ldi r6, 1
L_cmp_d55:
    stw r6, r7, 18
    ldw r4, r7, 18
    adi r4, r4, 0
    brnz L_skip56
    jal L_endwhile27
L_skip56:
    ldw r4, r7, 4
    stw r4, r7, 20
    ldw r4, r7, 2
    stw r4, r7, 22
    ldw r2, r7, 22
    ldw r1, r7, 20
    jal SdReadSec
    stw r1, r7, 24
    ldw r4, r7, 24
    stb r4, r7, 7
    ldb r4, r7, 7
    stw r4, r7, 26
    ldi r4, 0
    stw r4, r7, 28
    ldw r4, r7, 26
    ldw r5, r7, 28
    tst r4, r5
    brnz L_cmp_t57
    ldi r6, 0
    br L_cmp_d58
L_cmp_t57:
    ldi r6, 1
L_cmp_d58:
    stw r6, r7, 30
    ldw r4, r7, 30
    adi r4, r4, 0
    brnz L_skip59
    jal L_endif28
L_skip59:
    ldi r4, 1
    stw r4, r7, 32
    ldw r1, r7, 32
    jal L_ReadSecs_epilogue
L_endif28:
    ldw r4, r7, 4
    stw r4, r7, 34
    ldi r4, 512
    stw r4, r7, 36
    ldw r4, r7, 34
    ldw r5, r7, 36
    add r6, r4, r5
    stw r6, r7, 38
    ldw r4, r7, 38
    stw r4, r7, 4
    ldw r4, r7, 2
    stw r4, r7, 40
    ldi r4, 512
    stw r4, r7, 42
    ldw r4, r7, 40
    ldw r5, r7, 42
    add r6, r4, r5
    stw r6, r7, 44
    ldw r4, r7, 44
    stw r4, r7, 2
    ldw r4, r7, 0
    stw r4, r7, 46
    ldi r4, 1
    stw r4, r7, 48
    ldw r4, r7, 46
    ldw r5, r7, 48
    add r6, r4, r5
    stw r6, r7, 50
    ldw r4, r7, 50
    stw r4, r7, 0
    jal L_while26
L_endwhile27:
    ldi r4, 0
    stw r4, r7, 52
    ldw r1, r7, 52
    jal L_ReadSecs_epilogue
L_ReadSecs_epilogue:
    ldw r3, r7, 60
    ssp r3, r0
    ldw r4, r7, 54
    ldw r5, r7, 56
    ldw r6, r7, 58
    adi r7, r7, 62
    ret

; Function: DumpHex
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 44 bytes (locals=2, virtregs=32, params=2, saved=6)

DumpHex:
    adi r7, r7, -44
    stw r4, r7, 36
    stw r5, r7, 38
    stw r6, r7, 40
    stw r1, r7, 34
    lsp r3, r0
    stw r3, r7, 42
    ldi r4, 0
    stw r4, r7, 2
    ldw r4, r7, 2
    stw r4, r7, 0
L_while29:
    ldw r4, r7, 0
    stw r4, r7, 4
    ldi r4, 16
    stw r4, r7, 6
    ldw r4, r7, 4
    ldw r5, r7, 6
    tst r4, r5
    brult L_cmp_t60
    ldi r6, 0
    br L_cmp_d61
L_cmp_t60:
    ldi r6, 1
L_cmp_d61:
    stw r6, r7, 8
    ldw r4, r7, 8
    adi r4, r4, 0
    brnz L_skip62
    jal L_endwhile30
L_skip62:
    ldw r4, r7, 34
    stw r4, r7, 10
    ldw r4, r7, 0
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    add r6, r4, r5
    stw r6, r7, 14
    ldw r1, r7, 14
    jal LoadByte
    stw r1, r7, 16
    ldw r1, r7, 16
    jal PutHexByte
    ldw r4, r7, 0
    stw r4, r7, 18
    ldi r4, 15
    stw r4, r7, 20
    ldw r4, r7, 18
    ldw r5, r7, 20
    tst r4, r5
    brult L_cmp_t63
    ldi r6, 0
    br L_cmp_d64
L_cmp_t63:
    ldi r6, 1
L_cmp_d64:
    stw r6, r7, 22
    ldw r4, r7, 22
    adi r4, r4, 0
    brnz L_skip65
    jal L_endif31
L_skip65:
    ldi r4, 32
    stw r4, r7, 24
    ldw r1, r7, 24
    jal Emit
L_endif31:
    ldw r4, r7, 0
    stw r4, r7, 26
    ldi r4, 1
    stw r4, r7, 28
    ldw r4, r7, 26
    ldw r5, r7, 28
    add r6, r4, r5
    stw r6, r7, 30
    ldw r4, r7, 30
    stw r4, r7, 0
    jal L_while29
L_endwhile30:
    ldi r4, 10
    stw r4, r7, 32
    ldw r1, r7, 32
    jal Emit
    jal L_DumpHex_epilogue
L_DumpHex_epilogue:
    ldw r3, r7, 42
    ssp r3, r0
    ldw r4, r7, 36
    ldw r5, r7, 38
    ldw r6, r7, 40
    adi r7, r7, 44
    ret

; Function: main
; Visibility: STATIC, Return: VOID
; Params: 0, Frame: 60 bytes (locals=2, virtregs=50, params=0, saved=6)

main:
    adi r7, r7, -60
    stw r4, r7, 52
    stw r5, r7, 54
    stw r6, r7, 56
    lsp r3, r0
    stw r3, r7, 58
    ldi r4, msgInit
    stw r4, r7, 2
    ldw r1, r7, 2
    jal Putstr
    jal SdInit
    stw r1, r7, 4
    ldw r4, r7, 4
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 6
    ldi r4, 0
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    tst r4, r5
    brnz L_cmp_t66
    ldi r6, 0
    br L_cmp_d67
L_cmp_t66:
    ldi r6, 1
L_cmp_d67:
    stw r6, r7, 10
    ldw r4, r7, 10
    adi r4, r4, 0
    brnz L_skip68
    jal L_endif32
L_skip68:
    ldi r4, msgErr
    stw r4, r7, 12
    ldw r1, r7, 12
    jal Putstr
    ldb r4, r7, 1
    stw r4, r7, 14
    ldi r4, 48
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    add r6, r4, r5
    stw r6, r7, 18
    ldw r1, r7, 18
    jal Emit
    ldi r4, 10
    stw r4, r7, 20
    ldw r1, r7, 20
    jal Emit
    jal L_main_epilogue
L_endif32:
    ldi r4, msgOk
    stw r4, r7, 22
    ldw r1, r7, 22
    jal Putstr
    ldi r4, 81
    stw r4, r7, 24
    ldi r4, 1
    stw r4, r7, 26
    ldw r2, r7, 26
    ldw r1, r7, 24
    jal MapPage
    ldi r4, 82
    stw r4, r7, 28
    ldi r4, 2
    stw r4, r7, 30
    ldw r2, r7, 30
    ldw r1, r7, 28
    jal MapPage
    jal ReadSecs
    stw r1, r7, 32
    ldw r4, r7, 32
    stb r4, r7, 1
    ldb r4, r7, 1
    stw r4, r7, 34
    ldi r4, 0
    stw r4, r7, 36
    ldw r4, r7, 34
    ldw r5, r7, 36
    tst r4, r5
    brnz L_cmp_t69
    ldi r6, 0
    br L_cmp_d70
L_cmp_t69:
    ldi r6, 1
L_cmp_d70:
    stw r6, r7, 38
    ldw r4, r7, 38
    adi r4, r4, 0
    brnz L_skip71
    jal L_endif33
L_skip71:
    ldi r4, msgRdErr
    stw r4, r7, 40
    ldw r1, r7, 40
    jal Putstr
    jal L_main_epilogue
L_endif33:
    ldi r4, msgP1
    stw r4, r7, 42
    ldw r1, r7, 42
    jal Putstr
    ldi r4, 4096
    stw r4, r7, 44
    ldw r1, r7, 44
    jal DumpHex
    ldi r4, msgP2
    stw r4, r7, 46
    ldw r1, r7, 46
    jal Putstr
    ldi r4, 8192
    stw r4, r7, 48
    ldw r1, r7, 48
    jal DumpHex
    ldi r4, msgDone
    stw r4, r7, 50
    ldw r1, r7, 50
    jal Putstr
    jal L_main_epilogue
L_main_epilogue:
    ldw r3, r7, 58
    ssp r3, r0
    ldw r4, r7, 52
    ldw r5, r7, 54
    ldw r6, r7, 56
    adi r7, r7, 60
    ret


    .align 2

msgInit:
    .bytes "SD init...\x00"
msgOk:
    .bytes "OK\x0A\x00"
msgErr:
    .bytes "ERR \x00"
msgP1:
    .bytes "Page 1: \x00"
msgP2:
    .bytes "Page 2: \x00"
msgDone:
    .bytes "DONE\x0A\x00"
msgRdErr:
    .bytes "Read ERR\x0A\x00"
