; Generated by YAPL compiler Pass 4
; Source: test-frame.yapl


; Bootstrap startup code
; Stack initialized to 0x1000 (top of page 0)
_start:
    ldi r7, 4096
    jal main
    hlt

; Runtime library for YAPL

__shru16:
; Shift R1 right by R2 bits (logical)
    tst r2, r0
    brz L_shru_done
L_shru_loop:
    srl r1
    adi r2, r2, -1
    tst r2, r0
    brnz L_shru_loop
L_shru_done:
    ret

; Function: Putc
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 12 bytes (locals=0, virtregs=2, params=2, saved=6)

Putc:
    adi r7, r7, -12
    stw r4, r7, 4
    stw r5, r7, 6
    stw r6, r7, 8
    stw r1, r7, 2
    lsp r3, r0
    stw r3, r7, 10
    ldi r2 96
    ssp r1 r2
    br L_Putc_epilogue
L_Putc_epilogue:
    ldw r3, r7, 10
    ssp r3, r0
    ldw r4, r7, 4
    ldw r5, r7, 6
    ldw r6, r7, 8
    adi r7, r7, 12
    ret

; Function: Putnl
; Visibility: PUBLIC, Return: VOID
; Params: 0, Frame: 10 bytes (locals=0, virtregs=2, params=0, saved=6)

Putnl:
    adi r7, r7, -10
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    lsp r3, r0
    stw r3, r7, 8
    ldi r4, 10
    stw r4, r7, 0
    ldw r1, r7, 0
    jal Putc
    br L_Putnl_epilogue
L_Putnl_epilogue:
    ldw r3, r7, 8
    ssp r3, r0
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 10
    ret

; Function: PutHexNib
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 32 bytes (locals=0, virtregs=22, params=2, saved=6)

PutHexNib:
    adi r7, r7, -32
    stw r4, r7, 24
    stw r5, r7, 26
    stw r6, r7, 28
    stw r1, r7, 22
    lsp r3, r0
    stw r3, r7, 30
    ldw r4, r7, 22
    stw r4, r7, 0
    ldi r4, 10
    stw r4, r7, 2
    ldw r4, r7, 0
    ldw r5, r7, 2
    tst r4, r5
    brult L_cmp_t0
    ldi r6, 0
    br L_cmp_d1
L_cmp_t0:
    ldi r6, 1
L_cmp_d1:
    stw r6, r7, 4
    ldw r4, r7, 4
    adi r4, r4, 0
    brz L_else0
    ldw r4, r7, 22
    stw r4, r7, 6
    ldi r4, 48
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    add r6, r4, r5
    stw r6, r7, 10
    ldw r1, r7, 10
    jal Putc
    br L_endif1
L_else0:
    ldw r4, r7, 22
    stw r4, r7, 12
    ldi r4, 10
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    sub r6, r4, r5
    stw r6, r7, 16
    ldi r4, 65
    stw r4, r7, 18
    ldw r4, r7, 16
    ldw r5, r7, 18
    add r6, r4, r5
    stw r6, r7, 20
    ldw r1, r7, 20
    jal Putc
L_endif1:
    br L_PutHexNib_epilogue
L_PutHexNib_epilogue:
    ldw r3, r7, 30
    ssp r3, r0
    ldw r4, r7, 24
    ldw r5, r7, 26
    ldw r6, r7, 28
    adi r7, r7, 32
    ret

; Function: PutHexByte
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 26 bytes (locals=0, virtregs=16, params=2, saved=6)

PutHexByte:
    adi r7, r7, -26
    stw r4, r7, 18
    stw r5, r7, 20
    stw r6, r7, 22
    stw r1, r7, 16
    lsp r3, r0
    stw r3, r7, 24
    ldw r4, r7, 16
    stw r4, r7, 0
    ldi r4, 4
    stw r4, r7, 2
    ldw r1, r7, 0
    ldw r2, r7, 2
    jal __shru16
    stw r1, r7, 4
    ldi r4, 15
    stw r4, r7, 6
    ldw r4, r7, 4
    ldw r5, r7, 6
    and r6, r4, r5
    stw r6, r7, 8
    ldw r1, r7, 8
    jal PutHexNib
    ldw r4, r7, 16
    stw r4, r7, 10
    ldi r4, 15
    stw r4, r7, 12
    ldw r4, r7, 10
    ldw r5, r7, 12
    and r6, r4, r5
    stw r6, r7, 14
    ldw r1, r7, 14
    jal PutHexNib
    br L_PutHexByte_epilogue
L_PutHexByte_epilogue:
    ldw r3, r7, 24
    ssp r3, r0
    ldw r4, r7, 18
    ldw r5, r7, 20
    ldw r6, r7, 22
    adi r7, r7, 26
    ret

; Function: PutHexWord
; Visibility: PUBLIC, Return: VOID
; Params: 1, Frame: 22 bytes (locals=0, virtregs=12, params=2, saved=6)

PutHexWord:
    adi r7, r7, -22
    stw r4, r7, 14
    stw r5, r7, 16
    stw r6, r7, 18
    stw r1, r7, 12
    lsp r3, r0
    stw r3, r7, 20
    ldw r4, r7, 12
    stw r4, r7, 0
    ldi r4, 8
    stw r4, r7, 2
    ldw r1, r7, 0
    ldw r2, r7, 2
    jal __shru16
    stw r1, r7, 4
    ldw r1, r7, 4
    jal PutHexByte
    ldw r4, r7, 12
    stw r4, r7, 6
    ldi r4, 255
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    and r6, r4, r5
    stw r6, r7, 10
    ldw r1, r7, 10
    jal PutHexByte
    br L_PutHexWord_epilogue
L_PutHexWord_epilogue:
    ldw r3, r7, 20
    ssp r3, r0
    ldw r4, r7, 14
    ldw r5, r7, 16
    ldw r6, r7, 18
    adi r7, r7, 22
    ret

; Function: BigFunc
; Visibility: PUBLIC, Return: VOID
; Params: 15, Frame: 194 bytes (locals=36, virtregs=144, params=6, saved=6)

BigFunc:
    stw r4, r7, -8
    ldi r4, 194
    sub r7, r7, r4
    ldi r4, 188
    add r4, r7, r4
    stw r5, r4, 0
    ldi r4, 190
    add r4, r7, r4
    stw r6, r4, 0
    ldi r4, 180
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 182
    add r4, r7, r4
    stw r2, r4, 0
    ldi r4, 184
    add r4, r7, r4
    stw r3, r4, 0
    lsp r1, r0
    ldi r4, 192
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 180
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 36
    ldi r4, 1
    stw r4, r7, 38
    ldw r4, r7, 36
    ldw r5, r7, 38
    add r6, r4, r5
    stw r6, r7, 40
    ldw r4, r7, 40
    stw r4, r7, 34
    ldi r4, 182
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 42
    ldi r4, 2
    stw r4, r7, 44
    ldw r4, r7, 42
    ldw r5, r7, 44
    add r6, r4, r5
    stw r6, r7, 46
    ldw r4, r7, 46
    stb r4, r7, 33
    ldi r4, 184
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 48
    ldi r4, 3
    stw r4, r7, 50
    ldw r4, r7, 48
    ldw r5, r7, 50
    add r6, r4, r5
    stw r6, r7, 52
    ldw r4, r7, 52
    stw r4, r7, 30
    ldi r4, 194
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 54
    ldi r4, 4
    stw r4, r7, 56
    ldw r4, r7, 54
    ldw r5, r7, 56
    add r6, r4, r5
    stw r6, r7, 58
    ldw r4, r7, 58
    stb r4, r7, 29
    ldi r4, 196
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 60
    ldi r4, 5
    stw r4, r7, 62
    ldw r4, r7, 60
    ldw r5, r7, 62
    add r6, r4, r5
    ldi r3, 64
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 64
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 26
    ldi r4, 198
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 66
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 6
    ldi r3, 68
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 66
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 68
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 70
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 70
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 25
    ldi r4, 200
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 72
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 7
    ldi r3, 74
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 72
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 74
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 76
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 22
    ldi r4, 202
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 78
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 8
    ldi r3, 80
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 80
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 82
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 82
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 21
    ldi r4, 204
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 84
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 9
    ldi r3, 86
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 84
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 86
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 88
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 88
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 18
    ldi r4, 206
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 90
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 10
    ldi r3, 92
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 90
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 92
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 94
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 94
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 17
    ldi r4, 208
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 96
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 11
    ldi r3, 98
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 96
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 98
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 100
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 100
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 14
    ldi r4, 210
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 102
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 12
    ldi r3, 104
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 102
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 104
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 106
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 106
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 13
    ldi r4, 212
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 108
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 13
    ldi r3, 110
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 108
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 110
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 112
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 112
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 10
    ldi r4, 214
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 114
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 14
    ldi r3, 116
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 114
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 116
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 118
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 118
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 9
    ldi r4, 216
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 120
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 15
    ldi r3, 122
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 120
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 122
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 124
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 124
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 6
    ldw r4, r7, 34
    ldi r3, 126
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 18
    ldi r3, 128
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 126
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 128
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 130
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 130
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 4
    ldb r4, r7, 29
    ldi r3, 132
    add r3, r7, r3
    stw r4, r3, 0
    ldb r4, r7, 9
    ldi r3, 134
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 132
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 134
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 136
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 136
    add r4, r7, r4
    ldw r4, r4, 0
    stb r4, r7, 3
    ldw r4, r7, 26
    ldi r3, 138
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 30
    ldi r3, 140
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 138
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 140
    add r5, r7, r5
    ldw r5, r5, 0
    sub r6, r4, r5
    ldi r3, 142
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 142
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 0
    ldw r4, r7, 34
    ldi r3, 144
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 144
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 33
    ldi r3, 146
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 146
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 30
    ldi r3, 148
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 148
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 29
    ldi r3, 150
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 150
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 26
    ldi r3, 152
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 152
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 25
    ldi r3, 154
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 154
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 22
    ldi r3, 156
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 156
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 21
    ldi r3, 158
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 158
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 18
    ldi r3, 160
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 160
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 17
    ldi r3, 162
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 162
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 14
    ldi r3, 164
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 164
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 13
    ldi r3, 166
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 166
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 10
    ldi r3, 168
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 168
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 9
    ldi r3, 170
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 170
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 6
    ldi r3, 172
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 172
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldw r4, r7, 4
    ldi r3, 174
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 174
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    ldb r4, r7, 3
    ldi r3, 176
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 176
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexByte
    jal Putnl
    ldw r4, r7, 0
    ldi r3, 178
    add r3, r7, r3
    stw r4, r3, 0
    ldi r1, 178
    add r1, r7, r1
    ldw r1, r1, 0
    jal PutHexWord
    jal Putnl
    br L_BigFunc_epilogue
L_BigFunc_epilogue:
    ldi r3, 192
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldi r5, 188
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 190
    add r6, r7, r6
    ldw r6, r6, 0
    ldi r4, 186
    add r4, r7, r4
    ldw r2, r4, 0
    ldi r4, 194
    add r7, r7, r4
    mv r4, r2
    ret

; Function: main
; Visibility: STATIC, Return: VOID
; Params: 0, Frame: 38 bytes (locals=0, virtregs=30, params=0, saved=6)

main:
    adi r7, r7, -38
    stw r4, r7, 30
    stw r5, r7, 32
    stw r6, r7, 34
    lsp r3, r0
    stw r3, r7, 36
    ldi r4, 256
    stw r4, r7, 0
    ldi r4, 32
    stw r4, r7, 2
    ldi r4, 768
    stw r4, r7, 4
    ldi r4, 64
    stw r4, r7, 6
    ldi r4, 1280
    stw r4, r7, 8
    ldi r4, 96
    stw r4, r7, 10
    ldi r4, 1792
    stw r4, r7, 12
    ldi r4, 128
    stw r4, r7, 14
    ldi r4, 2304
    stw r4, r7, 16
    ldi r4, 160
    stw r4, r7, 18
    ldi r4, 2816
    stw r4, r7, 20
    ldi r4, 192
    stw r4, r7, 22
    ldi r4, 3328
    stw r4, r7, 24
    ldi r4, 224
    stw r4, r7, 26
    ldi r4, 3840
    stw r4, r7, 28
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r4, r7, 28
    adi r7, r7, -2
    stw r4, r7, 0
    ldw r3, r7, 28
    ldw r2, r7, 26
    ldw r1, r7, 24
    jal BigFunc
    adi r7, r7, 24
    br L_main_epilogue
L_main_epilogue:
    ldw r3, r7, 36
    ssp r3, r0
    ldw r4, r7, 30
    ldw r5, r7, 32
    ldw r6, r7, 34
    adi r7, r7, 38
    ret

