#!/bin/bash
# cc -### -O0 -std=c99 -Weverything -Wno-poison-system-directories *.c -o sim
cc -O0 -std=c99 -Weverything -Wno-unused-parameter -Wno-missing-field-initializers -Wno-declaration-after-statement -Wno-poison-system-directories *.c -o sim
# cc -### -O0 -std=c99 -Weverything *.c -o sim
