#!/bin/sh
# Clean-rebuild and run the editor from the sim/ folder.
# Usage: ./test [extra wut4-editor flags]
set -e

cd "$(dirname "$0")"

rm -f ./wut4-editor
(cd srv && go build -o ../wut4-editor ./cmd/wut4-editor)

exec ./wut4-editor --web-dir=./web --components-dir=./srv/components "$@"
