// Copyright (c) Jeff Berkowitz 2021, 2023. All Rights Reserved
// Automatically generated by Protogen - do not edit

package main

const ProtocolVersion = 11

func Ack(b byte) byte {
	return ^b
}

const CmdBase              = 0xE0
const CmdSync              = 0xEF
const CmdGetVer            = 0xEE
const CmdPoll              = 0xE9

const ErrNosync            = 0x80
const ErrPassive           = 0x81
const ErrOneclock          = 0x82
const ErrCantSs            = 0x83
const ErrCantPg            = 0x84
const ErrInternal          = 0x85
const ErrBadcmd            = 0x86

