; Generated by YAPL compiler Pass 4
; Source: lib/mmu.yapl

.code

; Runtime library for YAPL

__shru16:
; Shift R1 right by R2 bits (logical)
    tst r2, r0
    brz L_shru_done
L_shru_loop:
    srl r1
    adi r2, r2, -1
    tst r2, r0
    brnz L_shru_loop
L_shru_done:
    ret

__shlu16:
; Shift R1 left by R2 bits
    tst r2, r0
    brz L_shlu_done
L_shlu_loop:
    add r1, r1, r1
    adi r2, r2, -1
    tst r2, r0
    brnz L_shlu_loop
L_shlu_done:
    ret

; Function: writeMMU
; Visibility: STATIC, Return: VOID
; Params: 2, Frame: 14 bytes (locals=0, virtregs=2, params=4, saved=6)

writeMMU:
    adi r7, r7, -14
    stw r4, r7, 6
    stw r5, r7, 8
    stw r6, r7, 10
    stw r1, r7, 2
    stw r2, r7, 4
    lsp r3, r0
    stw r3, r7, 12
    ssp r2 r1
    jal L_writeMMU_epilogue
L_writeMMU_epilogue:
    ldw r3, r7, 12
    ssp r3, r0
    ldw r4, r7, 6
    ldw r5, r7, 8
    ldw r6, r7, 10
    adi r7, r7, 14
    ret

; Function: MapPage
; Visibility: PUBLIC, Return: VOID
; Params: 3, Frame: 94 bytes (locals=8, virtregs=72, params=6, saved=6)

MapPage:
    stw r4, r7, -8
    ldi r4, 94
    sub r7, r7, r4
    ldi r4, 88
    add r4, r7, r4
    stw r5, r4, 0
    ldi r4, 90
    add r4, r7, r4
    stw r6, r4, 0
    ldi r4, 80
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 82
    add r4, r7, r4
    stw r2, r4, 0
    ldi r4, 84
    add r4, r7, r4
    stw r3, r4, 0
    lsp r1, r0
    ldi r4, 92
    add r4, r7, r4
    stw r1, r4, 0
    ldi r4, 82
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 8
    ldi r4, 15
    stw r4, r7, 10
    ldw r4, r7, 8
    ldw r5, r7, 10
    tst r4, r5
    brult L_cmp_f2
    brz L_cmp_f2
    br L_cmp_t0
L_cmp_f2:
    ldi r6, 0
    br L_cmp_d1
L_cmp_t0:
    ldi r6, 1
L_cmp_d1:
    stw r6, r7, 12
    ldw r4, r7, 12
    adi r4, r4, 0
    brnz L_skip3
    jal L_endif0
L_skip3:
    die
L_endif0:
    ldi r4, 84
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 14
    ldi r4, 4095
    stw r4, r7, 16
    ldw r4, r7, 14
    ldw r5, r7, 16
    tst r4, r5
    brult L_cmp_f6
    brz L_cmp_f6
    br L_cmp_t4
L_cmp_f6:
    ldi r6, 0
    br L_cmp_d5
L_cmp_t4:
    ldi r6, 1
L_cmp_d5:
    stw r6, r7, 18
    ldw r4, r7, 18
    adi r4, r4, 0
    brnz L_skip7
    jal L_endif1
L_skip7:
    die
L_endif1:
    ldi r4, 80
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 20
    ldi r4, 1
    stw r4, r7, 22
    ldw r4, r7, 20
    ldw r5, r7, 22
    and r6, r4, r5
    stw r6, r7, 24
    ldi r4, 0
    stw r4, r7, 26
    ldw r4, r7, 24
    ldw r5, r7, 26
    tst r4, r5
    brnz L_cmp_t8
    ldi r6, 0
    br L_cmp_d9
L_cmp_t8:
    ldi r6, 1
L_cmp_d9:
    stw r6, r7, 28
    ldw r4, r7, 28
    adi r4, r4, 0
    brnz L_skip10
    jal L_else2
L_skip10:
    ldi r4, 64
    stw r4, r7, 30
    ldw r4, r7, 30
    stw r4, r7, 6
    jal L_endif3
L_else2:
    ldi r4, 32
    stw r4, r7, 32
    ldw r4, r7, 32
    stw r4, r7, 6
L_endif3:
    ldi r4, 80
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 34
    ldi r4, 2
    stw r4, r7, 36
    ldw r4, r7, 34
    ldw r5, r7, 36
    and r6, r4, r5
    stw r6, r7, 38
    ldw r4, r7, 38
    stw r4, r7, 0
    ldw r4, r7, 0
    stw r4, r7, 40
    ldi r4, 0
    stw r4, r7, 42
    ldw r4, r7, 40
    ldw r5, r7, 42
    tst r4, r5
    brz L_cmp_t11
    ldi r6, 0
    br L_cmp_d12
L_cmp_t11:
    ldi r6, 1
L_cmp_d12:
    stw r6, r7, 44
    ldw r4, r7, 44
    adi r4, r4, 0
    brnz L_skip13
    jal L_endif4
L_skip13:
    ldw r4, r7, 6
    stw r4, r7, 46
    ldi r4, 16
    stw r4, r7, 48
    ldw r4, r7, 46
    ldw r5, r7, 48
    add r6, r4, r5
    stw r6, r7, 50
    ldw r4, r7, 50
    stw r4, r7, 6
L_endif4:
    ldi r4, 80
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 52
    ldi r4, 12
    stw r4, r7, 54
    ldw r1, r7, 52
    ldw r2, r7, 54
    jal __shru16
    stw r1, r7, 56
    ldi r4, 3
    stw r4, r7, 58
    ldw r4, r7, 56
    ldw r5, r7, 58
    and r6, r4, r5
    stw r6, r7, 60
    ldw r4, r7, 60
    stw r4, r7, 2
    ldi r4, 84
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 62
    ldi r4, 4
    ldi r3, 64
    add r3, r7, r3
    stw r4, r3, 0
    ldw r1, r7, 62
    ldi r2, 64
    add r2, r7, r2
    ldw r2, r2, 0
    jal __shlu16
    ldi r3, 66
    add r3, r7, r3
    stw r1, r3, 0
    ldw r4, r7, 2
    ldi r3, 68
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 66
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 68
    add r5, r7, r5
    ldw r5, r5, 0
    or r6, r4, r5
    ldi r3, 70
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 70
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 4
    ldw r4, r7, 6
    ldi r3, 72
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 82
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 74
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 72
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 74
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 76
    add r3, r7, r3
    stw r6, r3, 0
    ldw r4, r7, 4
    ldi r3, 78
    add r3, r7, r3
    stw r4, r3, 0
    ldi r2, 78
    add r2, r7, r2
    ldw r2, r2, 0
    ldi r1, 76
    add r1, r7, r1
    ldw r1, r1, 0
    jal writeMMU
    jal L_MapPage_epilogue
L_MapPage_epilogue:
    ldi r3, 92
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldi r5, 88
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 90
    add r6, r7, r6
    ldw r6, r6, 0
    ldi r4, 86
    add r4, r7, r4
    ldw r2, r4, 0
    ldi r4, 94
    add r7, r7, r4
    mv r4, r2
    ret


.data
    .align 2

