#!/bin/bash
# Build and install YAPL compiler components
# Binaries are installed to GOBIN (typically ~/go/bin)
#
# For development, you can also build locally and set YAPL:
#   cd ylex && go build -o ylex . && cd ..
#   (repeat for yparse, ysem, ygen, ya)
#   export YAPL=/path/to/lang
#
cd "$(dirname "$0")"

cd ylex && go install && \
cd ../yparse && go install && \
cd ../ysem && go install && \
cd ../ygen && go install && \
cd ../ya && go install
