; Generated by YAPL compiler Pass 4
; Source: hello.yapl


; Bootstrap startup code
; Stack initialized to 0x1000 (top of page 0)
_start:
    ldi r7, 4096
    jal main
    hlt

; Function: main
; Visibility: STATIC, Return: VOID
; Params: 0, Frame: 8 bytes (locals=0, virtregs=2, saved=6)

main:
    adi r7, r7, -8
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    ldi r4, hello
    stw r4, r7, 0
    ldw r1, r7, 0
    jal putstr
L_main_epilogue:
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 8
    ret

; Function: putc
; Visibility: STATIC, Return: VOID
; Params: 1, Frame: 8 bytes (locals=0, virtregs=2, saved=6)

putc:
    adi r7, r7, -8
    stw r4, r7, 2
    stw r5, r7, 4
    stw r6, r7, 6
    ldi r2 96
    ssp r1 r2
L_putc_epilogue:
    ldw r4, r7, 2
    ldw r5, r7, 4
    ldw r6, r7, 6
    adi r7, r7, 8
    ret

; Function: putstr
; Visibility: STATIC, Return: VOID
; Params: 1, Frame: 24 bytes (locals=0, virtregs=18, saved=6)

putstr:
    adi r7, r7, -24
    stw r4, r7, 18
    stw r5, r7, 20
    stw r6, r7, 22
L_while0:
    mv r4, r1
    stw r4, r7, 0
    ldw r5, r7, 0
    ldw r4, r5, 0
    stw r4, r7, 2
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 2
    ldw r5, r7, 4
    tst r4, r5
    ldi r6, 1
    brnz L_cmp0
    ldi r6, 0
L_cmp0:
    stw r6, r7, 6
    ldw r4, r7, 6
    tst r4, r4
    brz L_endwhile1
    mv r4, r1
    stw r4, r7, 8
    ldw r5, r7, 8
    ldw r4, r5, 0
    stw r4, r7, 10
    ldw r1, r7, 10
    jal putc
    mv r4, r1
    stw r4, r7, 12
    ldi r4, 1
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    add r6, r4, r5
    stw r6, r7, 16
    ldw r4, r7, 16
    mv r1, r4
    br L_while0
L_endwhile1:
L_putstr_epilogue:
    ldw r4, r7, 18
    ldw r5, r7, 20
    ldw r6, r7, 22
    adi r7, r7, 24
    ret


    .align 2

hello:
    .bytes "hello, world.\x0A\x00"
