; Generated by YAPL compiler Pass 4
; Source: /Users/jeff/go/src/github.com/gmofishsauce/wut4/lang/itoa.yapl

.code

; Runtime library for YAPL

__divu16:
; Unsigned divide R1 / R2 -> R1 (quotient)
    ldi r3, 0
    ldi r4, 0
    ldi r5, 16
L_divu_loop:
    add r4, r4, r4
    mv r6, r1
    ldi r0, 15
    tst r1, r1
    brslt L_divu_setbit
    br L_divu_nobit
L_divu_setbit:
    adi r4, r4, 1
L_divu_nobit:
    add r1, r1, r1
    add r3, r3, r3
    tst r4, r2
    brult L_divu_next
    sub r4, r4, r2
    adi r3, r3, 1
L_divu_next:
    adi r5, r5, -1
    tst r5, r5
    brnz L_divu_loop
    mv r1, r3
    ret

__modu16:
; Unsigned modulo R1 % R2 -> R1
    ldi r4, 0
    ldi r5, 16
L_modu_loop:
    add r4, r4, r4
    tst r1, r1
    brslt L_modu_setbit
    br L_modu_nobit
L_modu_setbit:
    adi r4, r4, 1
L_modu_nobit:
    add r1, r1, r1
    tst r4, r2
    brult L_modu_next
    sub r4, r4, r2
L_modu_next:
    adi r5, r5, -1
    tst r5, r5
    brnz L_modu_loop
    mv r1, r4
    ret

; Function: reverse
; Visibility: STATIC, Return: VOID
; Params: 2, Frame: 77 bytes (locals=5, virtregs=62, params=4, saved=6)

reverse:
    stw r4, r7, -6
    ldi r4, 77
    sub r7, r7, r4
    ldi r3, 73
    add r3, r7, r3
    stw r5, r3, 0
    ldi r3, 75
    add r3, r7, r3
    stw r6, r3, 0
    stw r1, r7, 67
    stw r2, r7, 69
    ldi r4, 69
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 5
    ldi r4, 0
    stw r4, r7, 7
    ldw r4, r7, 5
    ldw r5, r7, 7
    tst r4, r5
    brult L_cmp_d1
    brz L_cmp_d1
    br L_cmp_t0
    ldi r6, 0
    br L_cmp_d1
L_cmp_t0:
    ldi r6, 1
L_cmp_d1:
    stw r6, r7, 9
    ldw r4, r7, 9
    adi r4, r4, 0
    brz L_endif0
    ldi r4, 0
    stw r4, r7, 11
    ldw r4, r7, 11
    stw r4, r7, 0
    ldi r4, 69
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 13
    ldi r4, 1
    stw r4, r7, 15
    ldw r4, r7, 13
    ldw r5, r7, 15
    sub r6, r4, r5
    stw r6, r7, 17
    ldw r4, r7, 17
    stw r4, r7, 2
L_while1:
    ldw r4, r7, 0
    stw r4, r7, 19
    ldw r4, r7, 2
    stw r4, r7, 21
    ldw r4, r7, 19
    ldw r5, r7, 21
    tst r4, r5
    brult L_cmp_t2
    ldi r6, 0
    br L_cmp_d3
L_cmp_t2:
    ldi r6, 1
L_cmp_d3:
    stw r6, r7, 23
    ldw r4, r7, 23
    adi r4, r4, 0
    brz L_endwhile2
    ldi r4, 67
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 25
    ldw r4, r7, 0
    stw r4, r7, 27
    ldw r4, r7, 25
    ldw r5, r7, 27
    add r6, r4, r5
    stw r6, r7, 29
    ldw r5, r7, 29
    ldb r4, r5, 0
    stw r4, r7, 31
    ldw r4, r7, 31
    stw r4, r7, 3
    ldi r4, 67
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 33
    ldw r4, r7, 2
    stw r4, r7, 35
    ldw r4, r7, 33
    ldw r5, r7, 35
    add r6, r4, r5
    stw r6, r7, 37
    ldw r5, r7, 37
    ldb r4, r5, 0
    stw r4, r7, 39
    ldi r4, 67
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 41
    ldw r4, r7, 0
    stw r4, r7, 43
    ldw r4, r7, 41
    ldw r5, r7, 43
    add r6, r4, r5
    stw r6, r7, 45
    ldw r4, r7, 39
    ldw r5, r7, 45
    stw r4, r5, 0
    ldw r4, r7, 3
    stw r4, r7, 47
    ldi r4, 67
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 49
    ldw r4, r7, 2
    stw r4, r7, 51
    ldw r4, r7, 49
    ldw r5, r7, 51
    add r6, r4, r5
    stw r6, r7, 53
    ldw r4, r7, 47
    ldw r5, r7, 53
    stw r4, r5, 0
    ldw r4, r7, 0
    stw r4, r7, 55
    ldi r4, 1
    stw r4, r7, 57
    ldw r4, r7, 55
    ldw r5, r7, 57
    add r6, r4, r5
    stw r6, r7, 59
    ldw r4, r7, 59
    stw r4, r7, 0
    ldw r4, r7, 2
    stw r4, r7, 61
    ldi r4, 1
    stw r4, r7, 63
    ldw r4, r7, 61
    ldw r5, r7, 63
    sub r6, r4, r5
    ldi r3, 65
    add r3, r7, r3
    stw r6, r3, 0
    ldi r4, 65
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 2
    br L_while1
L_endwhile2:
L_endif0:
L_reverse_epilogue:
    ldi r5, 73
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 75
    add r6, r7, r6
    ldw r6, r6, 0
    ldi r4, 71
    add r4, r7, r4
    ldw r2, r4, 0
    ldi r4, 77
    add r7, r7, r4
    mv r4, r2
    ret

; Function: Utoa
; Visibility: PUBLIC, Return: t35
; Params: 2, Frame: 88 bytes (locals=4, virtregs=72, params=4, saved=6)

Utoa:
    stw r4, r7, -6
    ldi r4, 88
    sub r7, r7, r4
    ldi r3, 84
    add r3, r7, r3
    stw r5, r3, 0
    ldi r3, 86
    add r3, r7, r3
    stw r6, r3, 0
    stw r1, r7, 76
    stw r2, r7, 78
    lsp r3, r0
    stw r3, r7, 80
    ldi r4, 0
    stw r4, r7, 4
    ldw r4, r7, 4
    stw r4, r7, 0
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 6
    ldi r4, 0
    stw r4, r7, 8
    ldw r4, r7, 6
    ldw r5, r7, 8
    tst r4, r5
    brz L_cmp_t4
    ldi r6, 0
    br L_cmp_d5
L_cmp_t4:
    ldi r6, 1
L_cmp_d5:
    stw r6, r7, 10
    ldw r4, r7, 10
    adi r4, r4, 0
    brz L_endif3
    ldi r4, 48
    stw r4, r7, 12
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 14
    ldw r4, r7, 12
    ldw r5, r7, 14
    stw r4, r5, 0
    ldi r4, 0
    stw r4, r7, 16
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 18
    ldi r4, 1
    stw r4, r7, 20
    ldw r4, r7, 18
    ldw r5, r7, 20
    add r6, r4, r5
    stw r6, r7, 22
    ldw r4, r7, 16
    ldw r5, r7, 22
    stw r4, r5, 0
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 24
L_endif3:
L_while4:
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 26
    ldi r4, 0
    stw r4, r7, 28
    ldw r4, r7, 26
    ldw r5, r7, 28
    tst r4, r5
    brnz L_cmp_t6
    ldi r6, 0
    br L_cmp_d7
L_cmp_t6:
    ldi r6, 1
L_cmp_d7:
    stw r6, r7, 30
    ldw r4, r7, 30
    adi r4, r4, 0
    brz L_endwhile5
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 32
    ldi r4, 10
    stw r4, r7, 34
    ldw r1, r7, 32
    ldw r2, r7, 34
    jal __modu16
    stw r1, r7, 36
    ldw r4, r7, 36
    stw r4, r7, 2
    ldw r4, r7, 2
    stw r4, r7, 38
    ldi r4, 48
    stw r4, r7, 40
    ldw r4, r7, 38
    ldw r5, r7, 40
    add r6, r4, r5
    stw r6, r7, 42
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 44
    ldw r4, r7, 0
    stw r4, r7, 46
    ldw r4, r7, 44
    ldw r5, r7, 46
    add r6, r4, r5
    stw r6, r7, 48
    ldw r4, r7, 42
    ldw r5, r7, 48
    stw r4, r5, 0
    ldw r4, r7, 0
    stw r4, r7, 50
    ldi r4, 1
    stw r4, r7, 52
    ldw r4, r7, 50
    ldw r5, r7, 52
    add r6, r4, r5
    stw r6, r7, 54
    ldw r4, r7, 54
    stw r4, r7, 0
    ldi r4, 76
    add r4, r7, r4
    ldw r4, r4, 0
    stw r4, r7, 56
    ldi r4, 10
    stw r4, r7, 58
    ldw r1, r7, 56
    ldw r2, r7, 58
    jal __divu16
    stw r1, r7, 60
    ldw r4, r7, 60
    ldi r3, 76
    add r3, r7, r3
    stw r4, r3, 0
    br L_while4
L_endwhile5:
    ldi r4, 0
    stw r4, r7, 62
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 64
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 0
    ldi r3, 66
    add r3, r7, r3
    stw r4, r3, 0
    ldi r4, 64
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r5, 66
    add r5, r7, r5
    ldw r5, r5, 0
    add r6, r4, r5
    ldi r3, 68
    add r3, r7, r3
    stw r6, r3, 0
    ldw r4, r7, 62
    ldi r5, 68
    add r5, r7, r5
    ldw r5, r5, 0
    stw r4, r5, 0
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 70
    add r3, r7, r3
    stw r4, r3, 0
    ldw r4, r7, 0
    ldi r3, 72
    add r3, r7, r3
    stw r4, r3, 0
    ldi r2, 72
    add r2, r7, r2
    ldw r2, r2, 0
    ldi r1, 70
    add r1, r7, r1
    ldw r1, r1, 0
    jal reverse
    ldi r4, 78
    add r4, r7, r4
    ldw r4, r4, 0
    ldi r3, 74
    add r3, r7, r3
    stw r4, r3, 0
L_Utoa_epilogue:
    ldi r3, 80
    add r3, r7, r3
    ldw r3, r3, 0
    ssp r3, r0
    ldi r5, 84
    add r5, r7, r5
    ldw r5, r5, 0
    ldi r6, 86
    add r6, r7, r6
    ldw r6, r6, 0
    ldi r4, 82
    add r4, r7, r4
    ldw r2, r4, 0
    ldi r4, 88
    add r7, r7, r4
    mv r4, r2
    ret

